import * as PIXI from 'pixi.js';
export declare class ScrollerBase extends PIXI.Container {
    private options;
    private ease;
    private content;
    private scrollbar;
    private _maskContent;
    private tickerFunction;
    private pointerDown;
    constructor(options: any);
    onDestroy(): void;
    get scrollbarOffsetHorizontal(): any;
    set scrollbarOffsetHorizontal(value: any);
    get scrollbarOffsetVertical(): any;
    set scrollbarOffsetVertical(value: any);
    private _disabled;
    get disable(): any;
    set disable(value: any);
    get stopPropagation(): any;
    set stopPropagation(value: any);
    get dragScroll(): any;
    set dragScroll(value: any);
    get boxWidth(): any;
    set boxWidth(value: any);
    get overflow(): any;
    set overflow(value: any);
    get overflowX(): any;
    set overflowX(value: any);
    get overflowY(): any;
    set overflowY(value: any);
    get boxHeight(): any;
    set boxHeight(value: any);
    get scrollbarSize(): any;
    set scrollbarSize(value: any);
    get contentWidth(): number;
    get contentHeight(): number;
    private _isScrollbarVertical;
    get isScrollbarVertical(): any;
    private _isScrollbarHorizontal;
    get isScrollbarHorizontal(): any;
    get scrollTop(): any;
    set scrollTop(top: any);
    get scrollLeft(): any;
    set scrollLeft(left: any);
    private _scrollWidth;
    get scrollWidth(): any;
    set scrollWidth(value: any);
    private _scrollHeight;
    get scrollHeight(): any;
    set scrollHeight(value: any);
    private scrollbarLeft;
    private scrollbarTop;
    private scrollbarWidth;
    private scrollbarHeight;
    private _drawScrollbars;
    private _drawMask;
    update(): void;
    private fade;
    updateLoop(elapsed: any): void;
    get dirty(): any;
    set dirty(value: any);
    activateFade(): void;
    scrollbarDown(e: any): void;
    scrollbarMove(e: any): void;
    scrollbarUp(): void;
    resize(options: any): void;
    ensureVisible(x: any, y: any, width: any, height: any): void;
}
//# sourceMappingURL=ScrollerBase.d.ts.map